### ISSUE TITLE
Wrong unlocked texture position

### ISSUE THREAD

**Issue by BannZay** [Qblolz/BigAuras#1]
1. Open addons settings
2. Click "BIG AURAS" -> "Player"
3. Check "Unlock"
4. Click "TEST MODE"

Expected: "trinket" frame on top of PlayerPortrait frame
Actual: "trinket" frame on wrong position

![изображение](https://user-images.githubusercontent.com/17499770/147634838-75b02213-0c51-4469-b061-e93031c810ea.png)

P.s.: dude, so much caps. We got it, it is big, really big, There is no need to caps that much =)

**Comment by BannZay** [comment]
Not related, but I didnt find an easy way to set player texture to the center of the screen (like it was done in Lose Control by default)

**Comment by Qblolz** [comment]
Srr for long answer - check new version and this behavior is "normal" for me like a developer
