### ISSUE TITLE
icon timers?

### ISSUE THREAD

**Issue by nogoodlife** [Qblolz/BigAuras#3]
Is there an option to see icon timers without onmiCC?

**Comment by Qblolz** [comment]
> Is there an option to see icon timers without onmiCC?

Nah. u can disable omniCC for this frames - add into blacklist (omniCC) by mask "BigAura_*"

**Comment by nogoodlife** [comment]
> > Is there an option to see icon timers without onmiCC?
> 
> Nah. u can disable omniCC for this frames - add into blacklist (omniCC) by mask "BigAura_*"

... I dont even have omniCC, basically I'm asking - how can i enable BigAuras timers, because i cant find any options for this?
![image](https://user-images.githubusercontent.com/100277966/171158035-beededb8-fd99-4c27-a073-6fa8183468cb.png)

**Comment by Extrimbx** [comment]
Не отображает кд на фреймах(сервер circle). Пробывал с OmniCC также не работает. Есть варианты что-бы можно отобразить кд с десятой доли секунд?

**Comment by Qblolz** [comment]
> > > Is there an option to see icon timers without onmiCC?
> > 
> > 
> > Nah. u can disable omniCC for this frames - add into blacklist (omniCC) by mask "BigAura_*"
> 
> ... I dont even have omniCC, basically I'm asking - how can i enable BigAuras timers, because i cant find any options for this? ![image](https://user-images.githubusercontent.com/100277966/171158035-beededb8-fd99-4c27-a073-6fa8183468cb.png)

I`m remove custom timer... cuz omniCC use less memory

**Comment by Qblolz** [comment]
> Не отображает кд на фреймах(сервер circle). Пробывал с OmniCC также не работает. Есть варианты что-бы можно отобразить кд с десятой доли секунд?

в omniCC есть такая настройка - отображать сотые посте какого-то таймера, покопайся. Так-же там минимальный шрифт для отображения таймера.
